const Level7 =[
    {id:1, cz:'přenos                  ', eng:'transfer'},
    {id:2, cz:'obecný, běžný, obvyklý        ', eng:'common'},
    {id:3, cz:'stoh, zásobník               ', eng:'stack'},
    {id:4, cz:'potvrdit např.příjem(ne confirm', eng:'acknowledge'},
    {id:5, cz:'potřesení rukou         ', eng:'handshake'},
    {id:6, cz:'nedostupný (ne unavailable)   ', eng:'unreachable'},
    {id:7, cz:'překročit                  ', eng:'exceed'},
    {id:8, cz:'pročistit (doslova spláchnout)', eng:'flush'},
    {id:9, cz:'sada protokolů             ', eng:'protocol suite'},
    {id:10, cz:'vytáčené spojení        ', eng:'dial-up connection'},
    {id:11, cz:'zásuvný modul                  ', eng:'snap-in'},
    {id:12, cz:'délka                    ', eng:'length'},
    {id:13, cz:'přenášet,předat dál(ne transmit', eng:'relay'},
    {id:14, cz:'občerstvit                  ', eng:'refresh'},
    {id:15, cz:'nadřazená (rodičovská) složka', eng:'parent folder'},
    {id:16, cz:'zpětné hledání          ', eng:'reverse lookup'},
    {id:17, cz:'podmíněný                  ', eng:'conditional'},
    {id:18, cz:'odpověď                  ', eng:'answer'},
    {id:19, cz:'zděděný                  ', eng:'inherited'},
    {id:20, cz:'řízení přístupu          ', eng:'access control'},
    {id:21, cz:'zřídit spojení          ', eng:'set up a connection'},
    {id:22, cz:'překlad                  ', eng:'translation'},
    {id:23, cz:'pořadí zpracování       ', eng:'processing order'},
    {id:24, cz:'na vyžádání                  ', eng:'on demand'},
    {id:25, cz:'vynutit                  ', eng:'enforce'},
    {id:26, cz:'harmonogram, časový plán', eng:'schedule'},
    {id:27, cz:'zamýšlený účel                ', eng:'intended purpose'},
    {id:28, cz:'registrace (ne registration)  ', eng:'enrolment'},
    {id:29, cz:'označit(ne highlight-zvýraznit)', eng:'mark'},
    {id:30, cz:'vydavatel                  ', eng:'publisher'},
    {id:31, cz:'karanténa                  ', eng:'quarantine'},
    {id:32, cz:'způsobilý, oprávněný k čemu', eng:'eligible'},
    {id:33, cz:'                              ', eng:'selftest'},
    {id:34, cz:'schválit (ne allow, permit)  ', eng:'approve'},
    {id:35, cz:'uspořádat (ne sort)        ', eng:'arrange'},
    {id:36, cz:'spojení (ne link, connection) ', eng:'association'},
    {id:37, cz:'zachytit, zaznamenat       ', eng:'capture'},
    {id:38, cz:'čištění                    ', eng:'cleanup'},
    {id:39, cz:'stát se současně, shodovat se s', eng:'coincide'},
    {id:40, cz:'sbírat (ne gather, pick)       ', eng:'collect'},
    {id:41, cz:'obsahovat                  ', eng:'contain'},
    {id:42, cz:'jádro                        ', eng:'core'},
    {id:43, cz:'využití procesoru       ', eng:'CPU utilization'},
    {id:44, cz:'prodleva                  ', eng:'delay'},
    {id:45, cz:'záviset na                  ', eng:'depend on'},
    {id:46, cz:'odvozený od                 ', eng:'derived from'},
    {id:47, cz:'navrhovat (např. síť)       ', eng:'design'},
    {id:48, cz:'trvání                  ', eng:'duration'},
    {id:49, cz:'vymáhání, vynucení       ', eng:'enforcement'},
    {id:50, cz:'zapsat do seznamu,zaregistrovat', eng:'enlist'},
    {id:51, cz:'výčet, vyjmenování       ', eng:'enumeration'},
    {id:52, cz:'vyhodnotit,ověřit,posoudit', eng:'evaluate'},
    {id:53, cz:'identifikovat, určit, zjistit', eng:'identify'},
    {id:54, cz:'okamžitě                  ', eng:'immediately'},
    {id:55, cz:'směřující dovnitř, příchozí', eng:'inbound'},
    {id:56, cz:'inventura                  ', eng:'inventory'},
    {id:57, cz:'latence, zdržení            ', eng:'latency'},
    {id:58, cz:'monitorovat,sledovat(ne observe', eng:'monitor'},
    {id:59, cz:'připojit(např.disk, ne connect)', eng:'mount'},
    {id:60, cz:'vyjednávání(např. o protokolu)', eng:'negotiation'},
    {id:61, cz:'pořadí (ne sequence)        ', eng:'order'},
    {id:62, cz:'táhnout (ne drag)           ', eng:'pull'},
    {id:63, cz:'vyčistit(ne clean),vymazat', eng:'purge'},
    {id:64, cz:'snížit, redukovat       ', eng:'reduce'},
    {id:65, cz:'řešit (překládat) dotazy (DNS)', eng:'resolve queries'},
    {id:66, cz:'získat zpět,vrátit,vyzvednout ', eng:'retrieve'},
    {id:67, cz:'zjistit, vyhledat informaci', eng:'retrieve'},
    {id:68, cz:'pravidlo                  ', eng:'rule'},
    {id:69, cz:'uspokojit požadavek       ', eng:'satisfy requirement'},
    {id:70, cz:'načasovaný,s nast.časem spuštěn', eng:'scheduled'},
    {id:71, cz:'rozštěpený, rozdělený        ', eng:'split'},
    {id:72, cz:'starý,neplatný(ne outdated,obs', eng:'stale'},
    {id:73, cz:'provoz přenášených dat       ', eng:'transfer traffic'},
    {id:74, cz:'přechod                  ', eng:'transition'},
    {id:75, cz:'spouštěcí akce              ', eng:'trigger'},
    {id:76, cz:'ověřit kým (ne verify by)     ', eng:'validate by'},
    {id:77, cz:'zahájit                     ', eng:'initiate'},
    {id:78, cz:'považovat                  ', eng:'consider'},
    {id:79, cz:'neočekávaně                 ', eng:'unexpectedly'},
    {id:80, cz:'vyvolávat co (ne excite)     ', eng:'invoke'},
    {id:81, cz:'důvěrný                    ', eng:'confidential'},
    {id:82, cz:'sledovat co, dodržovat co     ', eng:'observe'},
    {id:83, cz:'vyřadit z provozu          ', eng:'decommission'},
    {id:84, cz:'účinek (ne effect)            ', eng:'impact'},
    {id:85, cz:'vyjmenovat, vyčíslit        ', eng:'enumerate'},
    {id:86, cz:'odběr, předplatné           ', eng:'subscription'},
    {id:87, cz:'vzájemný, oboustranný', eng:'mutual'},
    {id:88, cz:'šířka pásma                ', eng:'bandwidth'},
    {id:89, cz:'práh                       ', eng:'threshold'},
    {id:90, cz:'náhrobek, záznam o smazaném', eng:'tombstone'},
    {id:91, cz:'úvodní byte                    ', eng:'preamble byte'},
    

]

export default Level7;