const Level6 =[
    {id:1, cz:'přesunout (ne shift)      ', eng:'move'},
    {id:2, cz:'balíček                   ', eng:'package'},
    {id:3, cz:'osobní                     ', eng:'personal'},
    {id:4, cz:'bez znaménka               ', eng:'unsigned'},
    {id:5, cz:'vývoj                      ', eng:'development'},
    {id:6, cz:'člen                      ', eng:'member'},
    {id:7, cz:'cesta (k souboru)         ', eng:'path'},
    {id:8, cz:'sezení                      ', eng:'session'},
    {id:9, cz:'aktuální (ne up to date)   ', eng:'current'},
    {id:10, cz:'zvyk                      ', eng:'custom'},
    {id:11, cz:'událost (ne case)         ', eng:'event'},
    {id:12, cz:'obraz                      ', eng:'image'},
    {id:13, cz:'několik (ne some)          ', eng:'several'},
    {id:14, cz:'zastaralý,starší verze(ne obso', eng:'legacy'},
    {id:15, cz:'tudíž,tedy (ne so, therefore)', eng:'thus'},
    {id:16, cz:'příslušný,odpovídající(ne corre', eng:'appropriate'},
    {id:17, cz:'přiřadit                  ', eng:'assign'},
    {id:18, cz:'koláček                    ', eng:'cookie'},
    {id:19, cz:'kořen                      ', eng:'root'},
    {id:20, cz:'bezdrátový                 ', eng:'wireless'},
    {id:21, cz:'řadič                     ', eng:'controller'},
    {id:22, cz:'ustavit, založit, zřídit  ', eng:'establish'},
    {id:23, cz:'uvést, prohlásit          ', eng:'state'},
    {id:24, cz:'neschopen                 ', eng:'unable'},
    {id:25, cz:'objevit,najít,zjistit(ne find)', eng:'discover'},
    {id:26, cz:'ještě, nadto, kromě toho  ', eng:'furthermore'},
    {id:27, cz:'soukromý                  ', eng:'private'},
    {id:28, cz:'cestovní (ne travel)      ', eng:'roaming'},
    {id:29, cz:'úložné místo, paměť       ', eng:'storage'},
    {id:30, cz:'přepínač, volba           ', eng:'switch'},
    {id:31, cz:'čaroděj, přeneseně:průvodce', eng:'wizard'},
    {id:32, cz:'ovlivnit                  ', eng:'affect'},
    {id:33, cz:'vymazat(ne erase,clear,remo', eng:'delete'},
    {id:34, cz:'přírůstkový                ', eng:'incremental'},
    {id:35, cz:'umístěný(ne placed,deployed)', eng:'located'},
    {id:36, cz:'běžící                   ', eng:'running'},
    {id:37, cz:'řešení                    ', eng:'solution'},
    {id:38, cz:'důvěryhodný                ', eng:'trusted'},
    {id:39, cz:'ověření při přihlašování  ', eng:'authentication'},
    {id:40, cz:'klávesa                   ', eng:'key'},
    {id:41, cz:'výzkum                     ', eng:'research'},
    {id:42, cz:'vytočit                   ', eng:'dial'},
    {id:43, cz:'vyřešit, přeložit         ', eng:'resolve'},
    {id:44, cz:'skrz                        ', eng:'through'},
    {id:45, cz:'zavést op.systém do paměti', eng:'boot'},
    {id:46, cz:'vymazat(ne delete,erase,remo', eng:'clear'},
    {id:47, cz:'úkol, úloha (ne job)           ', eng:'task'},
    {id:48, cz:'úspěšně                   ', eng:'successfully'},
    {id:49, cz:'obnovit,aktualizovat(ne restore', eng:'update'},
    {id:50, cz:'pokus, pokusit se (ne try)', eng:'attempt'},
    {id:51, cz:'vybrat (ne select, pick)  ', eng:'choose'},
    {id:52, cz:'vyžadovat(ne request,demand', eng:'require'},
    {id:53, cz:'sestávat se z, skládat se z', eng:'consist'},
    {id:54, cz:'pružný                     ', eng:'flexible'},
    {id:55, cz:'velké zdokonal. programu  ', eng:'upgrade'},
    {id:56, cz:'správce                     ', eng:'manager'},
    {id:57, cz:'pokročilý                 ', eng:'advanced'},
    {id:58, cz:'změnit                    ', eng:'change'},
    {id:59, cz:'spravovat,řídit(ne control)', eng:'manage'},
    {id:60, cz:'zpráva, hlásit             ', eng:'report'},
    {id:61, cz:'mezera,prostor            ', eng:'space'},
    {id:62, cz:'záložka (listu v Excelu)  ', eng:'tab'},
    {id:63, cz:'použít, aplikovat (ne use)', eng:'apply'},
    {id:64, cz:'ovladač                   ', eng:'driver'},
    {id:65, cz:'dělit se o, sdílet         ', eng:'share'},
    {id:66, cz:'provést (ne commit,execute)', eng:'perform'},
    {id:67, cz:'směrovač                   ', eng:'router'},
    {id:68, cz:'rozhraní                   ', eng:'interface'},
    {id:69, cz:'zabránit čemu               ', eng:'prevent from'},
    {id:70, cz:'přesměrovat (ne re-route) ', eng:'redirect'},
    {id:71, cz:'od (časově)              ', eng:'since'},
    {id:72, cz:'podpora, podporovat       ', eng:'support'},
    {id:73, cz:'ověřit si, prověřit           ', eng:'verify'},
    {id:74, cz:'nastavení(ne setting)    ', eng:'setup'},
    {id:75, cz:'odstranit(ne erase,delete,cle', eng:'remove'},
    {id:76, cz:'jednotlivý,osamocený,samostatný', eng:'single'},
    {id:77, cz:'brána                     ', eng:'gateway'},
    {id:78, cz:'režim                     ', eng:'mode'},
    {id:79, cz:'podsíť                     ', eng:'subnet'},
    {id:80, cz:'použít                     ', eng:'use'},
    {id:81, cz:'následující (ne next)    ', eng:'following'},
    {id:82, cz:'svazek                    ', eng:'volume'},
    {id:83, cz:'k dispozici, dostupný     ', eng:'available'},
    {id:84, cz:'darovat, přidělit, pověřit', eng:'grant'},
    {id:85, cz:'proto,tudíž,takže(ne thus,so)', eng:'therefore'},
    {id:86, cz:'obdržet,přijmout,dostat(ne acc ', eng:'receive'},
    {id:87, cz:'obnovit(ze zálohy)(ne recover)', eng:'restore'},
    {id:88, cz:'heslo                     ', eng:'password'},
    {id:89, cz:'předvést,ukázat,vystavit,ukázka', eng:'exhibit'},
    {id:90, cz:'adresář (ne složka -folder)', eng:'directory'},
    {id:91, cz:'vlastnost (ne feature)    ', eng:'property'},
    {id:92, cz:'upravit,změnit(ne edit,change)', eng:'modify'},
    {id:93, cz:'průzkumník                ', eng:'explorer'},
    {id:94, cz:'záloha                    ', eng:'backup'},
    {id:95, cz:'pasivovat,zneschopnit(ne inhibi', eng:'disable'},
    {id:96, cz:'zpráva (ne report)             ', eng:'message'},
    {id:97, cz:'nastavení (ne setup)    ', eng:'setting'},
    {id:98, cz:'řídit (ne manage)         ', eng:'control'},
    {id:99, cz:'testovat,ověřit(ne test,verify)', eng:'check'},
    {id:100, cz:'konto                     ', eng:'account'},
    {id:101, cz:'výpis, seznam             ', eng:'list'},
    {id:102, cz:'chyba (ne fault,failure,mistake', eng:'error'},
    {id:103, cz:'odpojený(tiskárna)(ne disconne', eng:'offline'},
    {id:104, cz:'záznam (ne record)        ', eng:'log'},
    {id:105, cz:'větev                     ', eng:'branch'},
    {id:106, cz:'stanoviště                ', eng:'site'},
    {id:107, cz:'volitelný                 ', eng:'optional'},
    {id:108, cz:'zařízení (ne equipment)      ', eng:'device'},
    {id:109, cz:'připojit(ne attach,join,add)', eng:'connect'},
    {id:110, cz:'vzdálený                  ', eng:'remote'},
    {id:111, cz:'připojit,doplnit(ne join,append', eng:'add'},
    {id:112, cz:'přenosný                     ', eng:'portable'},
    {id:113, cz:'vytvořit                  ', eng:'create'},
    {id:114, cz:'povolení, oprávnění       ', eng:'permission'},
    {id:115, cz:'předem nastavený(ne preset)', eng:'default'},
    {id:116, cz:'umožnit (ne allow-povolit)     ', eng:'enable'},
    {id:117, cz:'povolit (ne permit,approve) ', eng:'allow'},
    {id:118, cz:'bezpečnost (ne safety)    ', eng:'security'},
    {id:119, cz:'přístup                   ', eng:'access'},
    {id:120, cz:'složka (ne adr.-directory)', eng:'folder'},
    {id:121, cz:'soubor                    ', eng:'file'},
    {id:122, cz:'uživatel                  ', eng:'user'},
    {id:123, cz:'stát se současně (ne coincide)', eng:'collide'},

]

export default Level6;