const Level8 =[
    {id:1, cz:'přerušit,ukončit(ne break,inter', eng:'abort'},
    {id:2, cz:'připojit na konec,doplnit ', eng:'append'},
    {id:3, cz:'porovnat                  ', eng:'compare'},
    {id:4, cz:'podmínka                  ', eng:'condition'},
    {id:5, cz:'odstraňovat chyby (ne troublesh', eng:'debug'},
    {id:6, cz:'výraz (ne statement=příkaz)    ', eng:'expression'},
    {id:7, cz:'hromada, halda            ', eng:'heap'},
    {id:8, cz:'odsadit (při psaní)       ', eng:'indent'},
    {id:9, cz:'záznam,věta               ', eng:'record'},
    {id:10, cz:'odkaz,zmínka(ne referral) ', eng:'reference'},
    {id:11, cz:'odkaz (ne reference, link) ', eng:'referral'},
    {id:12, cz:'rozsah(ne span,range),r.platnos', eng:'scope'},
    {id:13, cz:'přerušit(ne pause,interrupt,abo', eng:'suspend'},
    {id:14, cz:'proměnná                  ', eng:'variable'},
    {id:15, cz:'uvozovky                  ', eng:'double quotes'},
    {id:16, cz: "'(apostrof, jednoduchá uvozovka)'" , eng:'single quote'},
    {id:17, cz:'kontrola, zda něco páruje ', eng:'pair matching'},
    {id:18, cz:'krokovat program (ne debug) ', eng:'trace'},
    {id:19, cz:'ukázat (ne point)         ', eng:'show'},
    {id:20, cz:'krok                      ', eng:'step'},
    {id:21, cz:'bod přerušení             ', eng:'breakpoint'},
    {id:22, cz:'vyhodnocení logic. výrazu ', eng:'boolean evaluation'},
    {id:23, cz:'podmíněný příkaz(ne command)', eng:'conditional statement'},
    {id:24, cz:'vnořená smyčka            ', eng:'nested loop'},
    {id:25, cz:'vývojový diagram          ', eng:'flow chart'},
    {id:26, cz:'ukázat (ne show)            ', eng:'point'},
    {id:27, cz:'ukazatel                    ', eng:'pointer'},
    {id:28, cz:'dědičnost                  ', eng:'inheritance'},
    {id:29, cz:'nasazení                       ', eng:'deployment'},
    {id:30, cz:'proud (ne flow)                ', eng:'stream'},
    {id:31, cz:'překladač                      ', eng:'compiler'},
    {id:32, cz:'příznak                        ', eng:'flag'},
    {id:33, cz:'spojit (řetězce)               ', eng:'concatenate'},
    {id:34, cz:'zásobník volání                ', eng:'call stack'},
    {id:35, cz:'zaváděcí program               ', eng:'loader'},
    {id:36, cz:'pasivovaný                ', eng:'disabled'},
    {id:37, cz:'start                     ', eng:'startup'},
    {id:38, cz:'jinak                     ', eng:'else'},
    {id:39, cz:'smyčka                    ', eng:'loop'},
    {id:40, cz:'zatímco                   ', eng:'while'},
    {id:41, cz:'spodní mez                ', eng:'lower bound'},
    {id:42, cz:'výstup                    ', eng:'output'},
    {id:43, cz:'#                         ', eng:'hash'},
    {id:44, cz:'ladicí program            ', eng:'debugger'},
    {id:45, cz:'počet                     ', eng:'count'},
    {id:46, cz:'zdrojový soubor           ', eng:'source file'},
    {id:47, cz:'podařit se                ', eng:'succeed'},
    {id:48, cz:'vyjmout,vyloučit(ne eliminate)', eng:'exclude'},
    {id:49, cz:'zahrnout, obsahovat(ne contain)', eng:'include'},
    {id:50, cz:'strop                     ', eng:'ceiling'},
    {id:51, cz:'podlaha                   ', eng:'floor'},
    {id:52, cz:'síla, výkon (ne performance)  ', eng:'power'},
    {id:53, cz:'návěští                   ', eng:'label'},
    {id:54, cz:'varování                  ', eng:'warning'},
    {id:55, cz:'vrátit (ne retrieve)        ', eng:'return '},
    {id:56, cz:'neplatný (ne invalid)     ', eng:'void'},
    {id:57, cz:'rezervace místa v paměti  ', eng:'memory allocation'},
    {id:58, cz:'nekonečno                 ', eng:'infinity'},
    {id:59, cz:'přetečení                 ', eng:'overflow'},
    {id:60, cz:'zabalit (ne pack)            ', eng:'wrap'},
    {id:61, cz:'ignor.rozdíl mezi m.a v.písm.', eng:'ignore case'},
    {id:62, cz:'čekat                     ', eng:'wait'},
    {id:63, cz:'ukončit(ne break,abort,finish)', eng:'terminate'},
    {id:64, cz:'sekvence volání           ', eng:'call sequence'},
    {id:65, cz:'různý, rozličný (ne various)', eng:'miscellaneous'},
    {id:66, cz:'hranice,okraj(ne outline:obrys)', eng:'border'},
    {id:67, cz:'omezení(ne restriction,limit)', eng:'constraints'},
    {id:68, cz:'výška                     ', eng:'height'},
    {id:69, cz:'šířka                     ', eng:'width'},
    {id:70, cz:'s měnitelným rozměrem     ', eng:'resizable'},
    {id:71, cz:'pole  (ne field)          ', eng:'array'},
    {id:72, cz:'interpunkční znaménko     ', eng:'punctuation'},
    {id:73, cz:'přírůstek                  ', eng:'increment'},
    {id:74, cz:'větvení                  ', eng:'choice'},
    {id:75, cz:'srovnání                 ', eng:'comparison'},
    {id:76, cz:'zdrojový kód              ', eng:'source code'},
    {id:77, cz:'kontrola, kontrolovat    ', eng:'check'},
    {id:78, cz:'prohození, prohodit      ', eng:'swap'},
    {id:79, cz:'řešení                     ', eng:'solution'},
    {id:80, cz:'vnořený (kaskád.) příkaz if', eng:'cascading if statement'},
    {id:81, cz:'naplnit pole             ', eng:'populate an array'},
    {id:82, cz:'rozhodovací příkaz       ', eng:'decision statement'},
    
]

export default Level8;