const Level4 =[
    {id:1, cz:'přístrojová deska auta     ', eng:'dashboard'},
    {id:2, cz:'přesný (ne precise)       ', eng:'exact'},
    {id:3, cz:'celkový (ne total)        ', eng:'overall'},
    {id:4, cz:'různý(ne different,miscellaneo', eng:'various'},
    {id:5, cz:'předpokládat              ', eng:'suppose'},
    {id:6, cz:'poznat                    ', eng:'recognize'},
    {id:7, cz:'postup,pokrok (ne progress)', eng:'advance'},
    {id:8, cz:'proveditelný              ', eng:'executable'},
    {id:9, cz:'umístěný (ne located)     ', eng:'placed'},
    {id:10, cz:'tok (ne stream)              ', eng:'flow'},
    {id:11, cz:'spustit,uvést v chod      ', eng:'launch'},
    {id:12, cz:'zvýraznit (ne mark-označit)  ', eng:'highlight'},
    {id:13, cz:'kromě (ne besides)           ', eng:'except'},
    {id:14, cz:'složený                   ', eng:'compound'},
    {id:15, cz:'za, mimo, nad             ', eng:'beyond'},
    {id:16, cz:'obejít (ne override)      ', eng:'bypass'},
    {id:17, cz:'úsilí,snaha               ', eng:'effort'},
    {id:18, cz:'stálý,trvalý(ne parmanent)', eng:'persistent'},
    {id:19, cz:'používat,využívat(ne use,utiliz', eng:'facilitate'},
    {id:20, cz:'zastaralý(ne outdated,legacy)', eng:'obsolete'},
    {id:21, cz:'v souladu s               ', eng:'consistent with'},
    {id:22, cz:'odpovídat čemu, splňovat  ', eng:'comply with'},
    {id:23, cz:'hlavní panel              ', eng:'taskbar'},
    {id:24, cz:'provést(ne perform,execute,acco', eng:'commit'},
    {id:25, cz:'získat(ne obtain,gain,acquire)', eng:'gather'},
    {id:26, cz:'získat(ne get,gather,acquire)', eng:'obtain'},
    {id:27, cz:'získat(ne gain,win,get,obtain)', eng:'acquire'},
    {id:28, cz:'získat(ne acquire,win,obtain,ge', eng:'gain'},
    {id:29, cz:'současný                  ', eng:'concurrent'},
    {id:30, cz:'připojení (ne link)       ', eng:'connection'},
    {id:31, cz:'samostatný                ', eng:'stand alone'},
    {id:32, cz:'drátem připojený          ', eng:'wired'},
    {id:33, cz:'vazba, provázání          ', eng:'binding'},
    {id:34, cz:'pořadí prohledávání       ', eng:'search order'},
    {id:35, cz:'výkon (ne power)              ', eng:'performance'},
    {id:36, cz:'poslat                    ', eng:'send'},
    {id:37, cz:'nepřerušitelný            ', eng:'uninterruptible'},
    {id:38, cz:'zdroj napájení            ', eng:'power supply'},
    {id:39, cz:'vybitá baterie            ', eng:'low battery'},
    {id:40, cz:'místní (ne native)            ', eng:'local'},
    {id:41, cz:'doba trvání hesla         ', eng:'password age'},
    {id:42, cz:'povolit (ne allow, approve) ', eng:'permit'},
    {id:43, cz:'rozprostřený              ', eng:'distributed'},
    {id:44, cz:'nečinný                   ', eng:'idle'},
    {id:45, cz:'poslední známý            ', eng:'last known'},
    {id:46, cz:'cestovat, toulat se       ', eng:'roam'},
    {id:47, cz:'oznamovací tón          ', eng:'dial tone'},
    {id:48, cz:'vyloučit oblast (ne area) ', eng:'exclude range'},
    {id:49, cz:'automatizovat             ', eng:'automate'},
    {id:50, cz:'zavěsit, odpojit linku    ', eng:'hang up'},
    {id:51, cz:'vysílat (ne broadcast)         ', eng:'transmit'},
    {id:52, cz:'výzva, náročný úkol(ne prompt)', eng:'challenge'},
    {id:53, cz:'odezva, reakce (ne reaction)  ', eng:'response'},
    {id:54, cz:'odpovídat na,reagovat      ', eng:'respond to'},
    {id:55, cz:'trvání propůjčení         ', eng:'lease duration'},
    {id:56, cz:'důvěřovat                 ', eng:'trust'},
    {id:57, cz:'nejvíce omezující         ', eng:'most restrictive'},
    {id:58, cz:'omezit přístup (ne deny)  ', eng:'restrict access'},
    {id:59, cz:'bezobslužný,bez přítomnosti', eng:'unattended'},
    {id:60, cz:'být přítomen              ', eng:'attend'},
    {id:61, cz:'volba (ne selection, choice)', eng:'option'},
    {id:62, cz:'ověření(ne authentication,verif', eng:'validation'},
    {id:63, cz:'mn.č. od mouse            ', eng:'mice'},
    {id:64, cz:'průchodnost               ', eng:'throughput'},
    {id:65, cz:'závažný (ne serious)      ', eng:'severe'},
    {id:66, cz:'jednoduchý                ', eng:'simple'},
    {id:67, cz:'udržovat, zachovat           ', eng:'maintain'},
    {id:68, cz:'údržba                   ', eng:'maintenance'},
    {id:69, cz:'volba (ne option, choice) ', eng:'selection'},
    {id:70, cz:'navrhovat (ne suggest)    ', eng:'propose'},
    {id:71, cz:'nasadit,zavést do praxe,realizo', eng:'implement'},
    {id:72, cz:'poskytovat                ', eng:'provide'},
    {id:73, cz:'zvýšit                   ', eng:'increase'},
    {id:74, cz:'prozradit, odkrýt         ', eng:'reveal'},
    {id:75, cz:'režie                     ', eng:'overhead'},
    {id:76, cz:'doručit, dodat            ', eng:'deliver'},
    {id:77, cz:'simulovat                 ', eng:'emulate'},
    {id:78, cz:'poškodit                  ', eng:'damage'},
    {id:79, cz:'odstranit,vyloučit(ne exclude)', eng:'eliminate'},
    {id:80, cz:'schopnost (ne ability)    ', eng:'capability'},
    {id:81, cz:'citlivý                   ', eng:'sensitive'},
    {id:82, cz:'výrazný (ne highlighted)    ', eng:'considerable'},
    {id:83, cz:'zachovat si,ponechat(ne preserv', eng:'retain'},
    {id:84, cz:'zachovat,uchovat(ne retain)', eng:'preserve'},
    {id:85, cz:'efektivní, výkonný        ', eng:'efficient'},
    {id:86, cz:'rozpětí,rozsah(ne scope,range)', eng:'span'},
    {id:87, cz:'pravidelný                ', eng:'regular'},
    {id:88, cz:'potkat (ne meet)          ', eng:'encounter'},
    {id:89, cz:'všeobecně použitelný      ', eng:'generic'},
    {id:90, cz:'způsobovat,důvod,příčina     ', eng:'cause'},
    {id:91, cz:'čekající na vyřízení      ', eng:'pending'},
    {id:92, cz:'vyhnout se                ', eng:'avoid'},
    {id:93, cz:'obejít (ne bypass)        ', eng:'override'},
    {id:94, cz:'použitelný (ne usable)    ', eng:'applicable'},
    {id:95, cz:'podmnožina                ', eng:'subset'},
    {id:96, cz:'zajistit (ne ensure,assert)  ', eng:'guarantee'},
    {id:97, cz:'zajistit(ne ensure,guarantee)', eng:'assert'},
    {id:98, cz:'zajistit(ne assert,guarantee)', eng:'ensure'},
    {id:99, cz:'zatížení, důraz           ', eng:'stress'},
    {id:100, cz:'zacházet,manipulovat(ne manipu', eng:'handle'},
    {id:101, cz:'měřit                     ', eng:'measure'},
    {id:102, cz:'čítač                     ', eng:'counter'},
    {id:103, cz:'loudavý                   ', eng:'sluggish'},
    {id:104, cz:'přílišný                  ', eng:'excessive'},
    {id:105, cz:'uváznutý                  ', eng:'stuck'},
    {id:106, cz:'volný (ne free)           ', eng:'loose'},
    {id:107, cz:'zničený,porušený(ne damaged)', eng:'corrupt(ed)'},
    {id:108, cz:'vyrovnávací paměť         ', eng:'buffer'},
    {id:109, cz:'všesměrový paket          ', eng:'broadcast'},
    {id:110, cz:'vyrovnávání zatížení      ', eng:'load balancing'},
    {id:111, cz:'řešení jména              ', eng:'name resolution'},
    {id:112, cz:'dopředné čtení            ', eng:'read ahead'},
    {id:113, cz:'dědění práv               ', eng:'rights inheritance'},
    {id:114, cz:'přípojka (port)           ', eng:'socket'},
    {id:115, cz:'odkládací soubor          ', eng:'swap file'},



]

export default Level4;