const Level1 =[
    {id:1, cz:'volitelný,jiný možný(ne optiona', eng:'alternative'},
    {id:2, cz:'klávesy šipek             ', eng:'arrow keys'},
    {id:3, cz:'hvězdička                 ', eng:'asterisk'},
    {id:4, cz:'zálohovat (ne store=uložit)', eng:'back up'},
    {id:5, cz:'obrácené lomítko          ', eng:'backslash'},
    {id:6, cz:'řádkové menu              ', eng:'bar menu'},
    {id:7, cz:'blikat                    ', eng:'blink'},
    {id:8, cz:'rámeček (ne frame)        ', eng:'box'},
    {id:9, cz:'přerušit (ne abort,interrupt, suspend)', eng:'break'},
    {id:10, cz:'vestavět, vestavěný       ', eng:'built in'},
    {id:11, cz:'zrušit,stornovat(ne discard)', eng:'cancel'},
    {id:12, cz:'velké písmeno(ne uppercase)', eng:'capital letter'},
    {id:13, cz:'deska, karta              ', eng:'card'},
    {id:14, cz:'kapitola                  ', eng:'chapter'},
    {id:15, cz:'znak  (ne sign)           ', eng:'character'},
    {id:16, cz:'vymazat (ne delete,clear, remove)', eng:'erase'},
    {id:17, cz:'zavřít                    ', eng:'close'},
    {id:18, cz:'dvojtečka                 ', eng:'colon'},
    {id:19, cz:'sloupec                   ', eng:'column'},
    {id:20, cz:'čárka ve větě             ', eng:'comma'},
    {id:21, cz:'zkrátit,vyjmout, vystřihnout', eng:'cut'},
    {id:22, cz:'pomlčka (ne hyphen)       ', eng:'dash'},
    {id:23, cz:'hustota                   ', eng:'density'},
    {id:24, cz:'tečka, bod (ne point)     ', eng:'dot'},
    {id:25, cz:'disková mechanika         ', eng:'disk drive'},
    {id:26, cz:'kopírování (ne copying)        ', eng:'duplication'},
    {id:27, cz:'upravit (text) (ne modify,change)', eng:'edit'},
    {id:28, cz:'selhat, nepodařit se      ', eng:'fail'},
    {id:29, cz:'vada,chyba(ne failure,error,mis', eng:'fault'},
    {id:30, cz:'číslice, diagram, obrázek      ', eng:'figure'},
    {id:31, cz:'najít                   ', eng:'find'},
    {id:32, cz:'všeobecný (ne common, universal) ', eng:'general'},
    {id:33, cz:'průvodce (ne wizard)      ', eng:'guide'},
    {id:34, cz:'skrýt,schovat             ', eng:'hide'},
    {id:35, cz:'pomlčka (ne dash)         ', eng:'hyphen'},
    {id:36, cz:'úvod                      ', eng:'introduction'},
    {id:37, cz:'neplatný  (ne void)         ', eng:'invalid'},
    {id:38, cz:'písmeno                   ', eng:'letter'},
    {id:39, cz:'řádek (ne row)            ', eng:'line'},
    {id:40, cz:'odřádkování               ', eng:'line-feed'},
    {id:41, cz:'zamknout,znepřístupnit    ', eng:'lock'},
    {id:42, cz:'vyhledání (ne search)         ', eng:'lookup'},
    {id:43, cz:'hodit se pasovat          ', eng:'match'},
    {id:44, cz:'matice                    ', eng:'matrix'},
    {id:45, cz:'příští,další (ne following) ', eng:'next'},
    {id:46, cz:'všimnout si               ', eng:'notice'},
    {id:47, cz:'připojený(tiskárna)       ', eng:'on-line'},
    {id:48, cz:'přepsat (ne rewrite)      ', eng:'overwrite'},
    {id:49, cz:'stránka                   ', eng:'page'},
    {id:50, cz:'část (ne portion, section)    ', eng:'part'},
    {id:51, cz:'sbírat,vybírat (ne select,collect)', eng:'pick'},
    {id:52, cz:'chránit,bránit            ', eng:'protect'},
    {id:53, cz:'tlačit,stisknout(ne press)', eng:'push'},
    {id:54, cz:'opustit,ukončit (ne cancel,exit)', eng:'quit'},
    {id:55, cz:'opustit(ne quit,cancel,leave)', eng:'exit'},
    {id:56, cz:'připraven                 ', eng:'ready'},
    {id:57, cz:'nahradit                  ', eng:'replace'},
    {id:58, cz:'znovu začít               ', eng:'resume'},
    {id:59, cz:'zkusit znovu (ne resume)  ', eng:'retry'},
    {id:60, cz:'přepsat (ne ovewrite)     ', eng:'rewrite'},
    {id:61, cz:'páska (ne tape)           ', eng:'ribbon'},
    {id:62, cz:'řada, řádek (ne line)     ', eng:'row'},
    {id:63, cz:'uložit, uschovat (ne store)', eng:'save'},
    {id:64, cz:'hledat(ne search,scan)    ', eng:'seek'},
    {id:65, cz:'procházet,prohledávat (ne seek)', eng:'scan'},
    {id:66, cz:'vybrat (ne choose, pick)  ', eng:'select'},
    {id:67, cz:'středník                  ', eng:'semicolon'},
    {id:68, cz:'věta                      ', eng:'sentence'},
    {id:69, cz:'nastavit (ne adjust)      ', eng:'set'},
    {id:70, cz:'posun,přeřaďovač          ', eng:'shift'},
    {id:71, cz:'velikost,rozměr           ', eng:'size'},
    {id:72, cz:'lomítko                   ', eng:'slash'},
    {id:73, cz:'stojící samostatně (ne single)', eng:'standalone'},
    {id:74, cz:'uložit(data) (ne save), úložiště', eng:'store'},
    {id:75, cz:'zapnout (ne turn on)      ', eng:'switch on'},
    {id:76, cz:'teplota                   ', eng:'temperature'},
    {id:77, cz:'přepínat (ne switch,swap)  ', eng:'toggle'},
    {id:78, cz:'téma (ne theme)           ', eng:'topic'},
    {id:79, cz:'celkový(ne overall), celk.součet', eng:'total'},
    {id:80, cz:'stopa, sledovat           ', eng:'track'},
    {id:81, cz:'neautorizovaný            ', eng:'unauthorized'},
    {id:82, cz:'aktualizovaný(ne refreshed)', eng:'updated'},
    {id:83, cz:'pohled, prohlédnout       ', eng:'view'},
    {id:84, cz:'dvojkový                  ', eng:'binary'},
    {id:85, cz:'úroveň (ne grade)         ', eng:'level'},
    {id:86, cz:'nedostatečný              ', eng:'insufficient'},
    {id:87, cz:'prázdný (ne blank)        ', eng:'empty'},
    {id:88, cz:'zadat, vložit (ne insert) ', eng:'enter'},
    {id:89, cz:'datum                     ', eng:'date'},
    {id:90, cz:'jistý  (ne certain)       ', eng:'sure'},
    {id:91, cz:'chybět                    ', eng:'miss'},
    {id:92, cz:'neúspěch,závada, porucha(ne faul', eng:'failure'},
    {id:93, cz:'obnovit(ne restore,update,refresh', eng:'recover'},
    {id:94, cz:'pokračovat (ne continue,resume)', eng:'proceed'},
    {id:95, cz:'jiný, další (ne other,next)', eng:'another'},
    {id:96, cz:'skrytý                    ', eng:'hidden'},
    {id:97, cz:'více                      ', eng:'more'},
    {id:98, cz:'krátký, stručný (ne short)', eng:'brief'},
    {id:99, cz:'plný,nezkrácený (např.výpis)', eng:'full'},
    {id:100, cz:'přepínat (ne switch,toggle)', eng:'swap'},
    {id:101, cz:'viditelný                 ', eng:'visible'},
    {id:102, cz:'rychlý (ne quick)              ', eng:'fast'},
    {id:103, cz:'ani, žádný                 ', eng:'neither'},
    {id:104, cz:'dokonce i                    ', eng:'even'},




]

export default Level1;