const Level5 =[
    {id:1, cz:'dosáhnout (ne reach)      ', eng:'achieve'},
    {id:2, cz:'výstraha, poplach         ', eng:'alert'},
    {id:3, cz:'pokračovat (ne proceed,resume)', eng:'continue'},
    {id:4, cz:'podnikový, firemní           ', eng:'corporate'},
    {id:5, cz:'cíl                        ', eng:'destination'},
    {id:6, cz:'určit,rozhodnout(ne decide)', eng:'determine'},
    {id:7, cz:'vybavený                  ', eng:'equipped'},
    {id:8, cz:'odchozí                   ', eng:'outbound'},
    {id:9, cz:'zastaralý,starší verze(ne obsol', eng:'outdated'},
    {id:10, cz:'stálý,trvalý(ne persistent)', eng:'permanent'},
    {id:11, cz:'připravovat               ', eng:'prepare'},
    {id:12, cz:'dosáhnout (ne achieve)    ', eng:'reach'},
    {id:13, cz:'předložit, podat           ', eng:'submit'},
    {id:14, cz:'dočasný                   ', eng:'temporary'},
    {id:15, cz:'jednotka                  ', eng:'unit'},
    {id:16, cz:'využití (ne usage)        ', eng:'utilization'},
    {id:17, cz:'most                      ', eng:'bridge'},
    {id:18, cz:'knoflík, tlačítko         ', eng:'button'},
    {id:19, cz:'žádoucí, vhodný           ', eng:'desired'},
    {id:20, cz:'přípona, prodloužení      ', eng:'extension'},
    {id:21, cz:'často (ne often)           ', eng:'frequently'},
    {id:22, cz:'vstup (ne entry)          ', eng:'input'},
    {id:23, cz:'položka                   ', eng:'item'},
    {id:24, cz:'zámek, ochrana            ', eng:'protection'},
    {id:25, cz:'nedávný,minulý(ne last,previou', eng:'recent'},
    {id:26, cz:'uskutečnit,vykonat(ne execute)', eng:'accomplish'},
    {id:27, cz:'odpovídající,splňující požad.', eng:'compliant'},
    {id:28, cz:'soulad s, vyhovění čemu, dodržo', eng:'compliance'},
    {id:29, cz:'potvrdit (ne acknowledge)  ', eng:'confirm'},
    {id:30, cz:'podnik                    ', eng:'enterprise'},
    {id:31, cz:'povinný (ne obligatory)       ', eng:'mandatory'},
    {id:32, cz:'zakázaný(ne denied,restricted)', eng:'prohibited'},
    {id:33, cz:'oprava (ne correction),opravit', eng:'repair'},
    {id:34, cz:'špatný                      ', eng:'wrong'},
    {id:35, cz:'prohlížet                 ', eng:'browse'},
    {id:36, cz:'okolí, prostředí          ', eng:'environment'},
    {id:37, cz:'spustit,vykonat(ne perform,laun', eng:'execute'},
    {id:38, cz:'určitý,konkrétní(ne specific)', eng:'particular'},
    {id:39, cz:'oblast (ne area, scope)   ', eng:'range'},
    {id:40, cz:'výsledek                 ', eng:'result'},
    {id:41, cz:'podpis                      ', eng:'signature'},
    {id:42, cz:'zdroj (ne supply,resource)', eng:'source'},
    {id:43, cz:'zdroj (ne supply,source)', eng:'resource'},
    {id:44, cz:'zdroj (ne resource,source)', eng:'supply'},
    {id:45, cz:'pruh                      ', eng:'stripe'},
    {id:46, cz:'trasa, následovat,kopírovat', eng:'trace'},
    {id:47, cz:'platný                      ', eng:'valid'},
    {id:48, cz:'hodnota                   ', eng:'value'},
    {id:49, cz:'pozadí                    ', eng:'background'},
    {id:50, cz:'jistý (ne sure)            ', eng:'certain'},
    {id:51, cz:'výjimka                   ', eng:'exception'},
    {id:52, cz:'neúspěšný (ne unsuccessful)', eng:'failed'},
    {id:53, cz:'pokrok (ne advance)       ', eng:'progress'},
    {id:54, cz:'za předpokladu, že        ', eng:'provided'},
    {id:55, cz:'příbuzný                  ', eng:'related'},
    {id:56, cz:'uvolnit(např.tlačítko myši)', eng:'release'},
    {id:57, cz:'řešit                     ', eng:'solve'},
    {id:58, cz:'přes                      ', eng:'via'},
    {id:59, cz:'uvnitř, v mezích          ', eng:'within'},
    {id:60, cz:'schopnost (ne capability) ', eng:'ability'},
    {id:61, cz:'slučitelnost            ', eng:'compatibility'},
    {id:62, cz:'denně                      ', eng:'daily'},
    {id:63, cz:'položka, vstup (ne input) ', eng:'entry'},
    {id:64, cz:'příklad                 ', eng:'example'},
    {id:65, cz:'rychle (ne fast)             ', eng:'quickly'},
    {id:66, cz:'přijmout  (ne receive)      ', eng:'accept'},
    {id:67, cz:'příchozí                 ', eng:'incoming'},
    {id:68, cz:'vsunout, vložit           ', eng:'insert'},
    {id:69, cz:'původní (ne initial)           ', eng:'original'},
    {id:70, cz:'část (ne part)             ', eng:'portion'},
    {id:71, cz:'oddělený                  ', eng:'separate'},
    {id:72, cz:'chytrý (ne wise, clever)  ', eng:'smart'},
    {id:73, cz:'ověření(ne authentication,valid', eng:'verification'},
    {id:74, cz:'objevit se (ne occur)    ', eng:'appear'},
    {id:75, cz:'objevit se,nastat(ne appear,hap', eng:'occur'},
    {id:76, cz:'případ (ne event)          ', eng:'case'},
    {id:77, cz:'pověření (jméno a konto)  ', eng:'credentials'},
    {id:78, cz:'zakázat(ne prohibit,restrict)', eng:'deny'},
    {id:79, cz:'režim spánku               ', eng:'hibernation'},
    {id:80, cz:'spoj, spojit (ne join)     ', eng:'link'},
    {id:81, cz:'prostředek                ', eng:'means'},
    {id:82, cz:'bod (ne dot)              ', eng:'point'},
    {id:83, cz:'společný fond             ', eng:'pool'},
    {id:84, cz:'obrazovka                 ', eng:'screen'},
    {id:85, cz:'nástroj                   ', eng:'tool'},
    {id:86, cz:'odlišný,alternativní(ne differe', eng:'alternate'},
    {id:87, cz:'odhalení,detekce          ', eng:'detection'},
    {id:88, cz:'odpojit (ne detach)       ', eng:'disconnect'},
    {id:89, cz:'správný (ne correct)      ', eng:'proper'},
    {id:90, cz:'hledat(ne seek,scan,lookup)', eng:'search'},
    {id:91, cz:'odstraňovat chyby (ne debug)', eng:'troubleshoot'},
    {id:92, cz:'množství                 ', eng:'amount'},
    {id:93, cz:'kazeta                      ', eng:'cartridge'},
    {id:94, cz:'připojitelnost,kvalita přip.', eng:'connectivity'},
    {id:95, cz:'zkoumat (ne explore)          ', eng:'examine'},
    {id:96, cz:'hostitel, hostit             ', eng:'host'},
    {id:97, cz:'vícenásobný, mnohý             ', eng:'multiple'},
    {id:98, cz:'násobit                   ', eng:'multiply'},
    {id:99, cz:'poznámka                  ', eng:'note'},
    {id:100, cz:'vlastnictví                 ', eng:'ownership'},
    {id:101, cz:'znovu nastavit            ', eng:'reset'},
    {id:102, cz:'řešení problémů          ', eng:'troubleshooting'},
    {id:103, cz:'obsah                     ', eng:'content'},
    {id:104, cz:'umístit,nasadit(ne locate,place', eng:'deploy'},
    {id:105, cz:'podobně(ne similarly)        ', eng:'likely'},
    {id:106, cz:'vyjmenovaný,zapsaný v sezn', eng:'listed'},
    {id:107, cz:'výzva (v přík.řádku),podnět  ', eng:'prompt'},
    {id:108, cz:'bezpečný (ne secure)         ', eng:'safe'},
    {id:109, cz:'dodatečný, další          ', eng:'additional'},
    {id:110, cz:'pruh (ne stripe)          ', eng:'bar'},
    {id:111, cz:'založený na                 ', eng:'based'},
    {id:112, cz:'šifrovat                 ', eng:'encrypt'},
    {id:113, cz:'rozbočovač                ', eng:'hub'},
    {id:114, cz:'vydání(needition,release),vydat', eng:'issue'},
    {id:115, cz:'jazyk                      ', eng:'language'},
    {id:116, cz:'zhustit,stlačit(ne compress)', eng:'pack'},
    {id:117, cz:'oddíl                      ', eng:'partition'},
    {id:118, cz:'technik                  ', eng:'technician'},
    {id:119, cz:'rys, vlastnost(ne property)', eng:'feature'},
    {id:120, cz:'zavést do paměti (ne boot)', eng:'load'},
    {id:121, cz:'umístění                 ', eng:'location'},
    {id:122, cz:'předchozí                 ', eng:'previous'},
    {id:123, cz:'žádat,žádost(ne require,demand)', eng:'request'},
    {id:124, cz:'řešení, překlad, rozlišení ', eng:'resolution'},
    {id:125, cz:'kdykoliv                 ', eng:'whenever'},
    {id:126, cz:'zaměstnanec               ', eng:'employee'},
    {id:127, cz:'zahrnout (ne comprise)    ', eng:'include'},
    {id:128, cz:'páteř', eng:'backbone'},
    {id:129, cz:'rozvaděč', eng:'rack'},
    {id:130, cz:'propojovací kabel', eng:'patch cord'},
    {id:131, cz:'přeslech mezi vodiči', eng:'cross talk'},
    {id:132, cz:'křížený kabel', eng:'crossover cable'},


]

export default Level5;