const Level2 =[
{id:1, cz:'strom                     ', eng:'tree'},
{id:2, cz:'adresář s podřízenými adr.', eng:'folder hierarchy'},
{id:3, cz:'komprimovat (ne pack)     ', eng:'compress'},
{id:4, cz:'stisknout (ne push, hit)  ', eng:'press'},
{id:5, cz:'jakýkoliv                 ', eng:'any'},
{id:6, cz:'příkazy šedě(nepřístupné) ', eng:'dimmed commands'},
{id:7, cz:'nepřístupný (příkaz)(ne unreach', eng:'unavailable'},
{id:8, cz:'pasivovat zaškrt.políčko  ', eng:'clear check box'},
{id:9, cz:'vybrat zaškrtávací políčko', eng:'select check box'},
{id:10, cz:'částečně vybrané zaškrt.pol.', eng:'shaded check box'},
{id:11, cz:'velikost písma            ', eng:'font size'},
{id:12, cz:'velikost písma v bodech   ', eng:'point size'},
{id:13, cz:'tučný                     ', eng:'bold'},
{id:14, cz:'kurzíva                   ', eng:'italic'},
{id:15, cz:'podtržený (ne underscored)', eng:'underlined'},
{id:16, cz:'podsazení, dolní index    ', eng:'subscript'},
{id:17, cz:'nadsazení, horní index    ', eng:'superscript'},
{id:18, cz:'textový kurzor            ', eng:'insertion point'},
{id:19, cz:'kurzor myši               ', eng:'mouse pointer'},
{id:20, cz:'klávesová zkratka,zástupce', eng:'shortcut'},
{id:21, cz:'táhni a pusť              ', eng:'drag-and-drop'},
{id:22, cz:'posuvník(přetáčecí lišta) ', eng:'scroll bar'},
{id:23, cz:'požadavek,nároky(ne demand)', eng:'requirement'},
{id:24, cz:'ponechat                  ', eng:'leave'},
{id:25, cz:'beze změn(ne without change', eng:'intact'},
{id:26, cz:'původní,počáteční(ne original) ', eng:'initial'},
{id:27, cz:'doporučovat               ', eng:'recommend'},
{id:28, cz:'přinejmenším              ', eng:'at least'},
{id:29, cz:'podle potřeby             ', eng:'as needed'},
{id:30, cz:'používá se                ', eng:'in use'},
{id:31, cz:'ze seznamu                ', eng:'from list'},
{id:32, cz:'šetřič obrazovky          ', eng:'screen saver'},
{id:33, cz:'velké (písmeno ne capital)', eng:'uppercase'},
{id:34, cz:'malé (písmeno)            ', eng:'lowercase'},
{id:35, cz:'stavový řádek, pruh (ne line)', eng:'status bar'},
{id:36, cz:'přílohy                   ', eng:'attachment'},
{id:37, cz:'znak konce odstavce       ', eng:'paragraph mark'},
{id:38, cz:'výskyt (ne presence)      ', eng:'occurrence'},
{id:39, cz:'kontrola                  ', eng:'check'},
{id:40, cz:'opravit (ne repair)       ', eng:'correct'},
{id:41, cz:'nastavit pozici(ne set...)', eng:'adjust position'},
{id:42, cz:'prázdný řádek (ne empty)  ', eng:'blank line'},
{id:43, cz:'vybraný text (ne selected)', eng:'highlighted text'},
{id:44, cz:'obrysy (ne border: okraj)     ', eng:'outline'},
{id:45, cz:'přerušit(ne break,abort,suspend', eng:'interrupt'},
{id:46, cz:'šablona (styl dokumentu)  ', eng:'template'},
{id:47, cz:'popisek(např.obrázku,ne descrip', eng:'caption'},
{id:48, cz:'táhnout (ne pull)          ', eng:'drag'},
{id:49, cz:'změnit velikost           ', eng:'resize'},
{id:50, cz:'vzhledem k(ne according to)  ', eng:'relative to'},
{id:51, cz:'sbalit (nabídku,ne soubor)', eng:'collapse'},
{id:52, cz:'rozbalit (ne explode)     ', eng:'expand'},
{id:53, cz:'povýšit,zvýšit hierar. úroveň', eng:'promote'},
{id:54, cz:'snížit (hierar. úroveň)   ', eng:'demote'},
{id:55, cz:'příruční (místní) nabídka ', eng:'shortcut menu'},
{id:56, cz:'upravit,upravit si(ne modify)', eng:'customize'},
{id:57, cz:'pravopis                  ', eng:'spelling'},
{id:58, cz:'korektor překlepů         ', eng:'spell checker'},
{id:59, cz:'poznámky (ne notes)       ', eng:'annotations'},
{id:60, cz:'souhrnné informace        ', eng:'summary info'},
{id:61, cz:'ukázka před tiskem        ', eng:'print preview'},
{id:62, cz:'záhlaví,hlavička(ne heading)', eng:'header'},
{id:63, cz:'pata, patička             ', eng:'footer'},
{id:64, cz:'velikost papíru           ', eng:'paper size'},
{id:65, cz:'na výšku (orientace       ', eng:'portrait'},
{id:66, cz:'na šířku (orientace)      ', eng:'landscape'},
{id:67, cz:'odstavec                  ', eng:'paragraph'},
{id:68, cz:'zarovnání (odstavce)      ', eng:'alignment'},
{id:69, cz:'naposledy použité(ne lastly...)', eng:'recently used'},
{id:70, cz:'rozlišovat malá a velká   ', eng:'match case'},
{id:71, cz:'rozlišení velkých písmen(ne mat', eng:'case sensitivity'},
{id:72, cz:'nástrojový pruh           ', eng:'toolbar'},
{id:73, cz:'dopředu                   ', eng:'forward'},
{id:74, cz:'dozadu                    ', eng:'backward'},
{id:75, cz:'tabulkový procesor        ', eng:'spreadsheet'},
{id:76, cz:'buňka tabulky               ', eng:'cell'},
{id:77, cz:'zadávat data              ', eng:'enter data'},
{id:78, cz:'desetinná místa           ', eng:'decimal places'},
{id:79, cz:'zalamování textu          ', eng:'text wrapping'},
{id:80, cz:'přetékat (do soused.buněk)', eng:'overflow'},
{id:81, cz:'rovnítko                  ', eng:'equal sign'},
{id:82, cz:'operátor dělení           ', eng:'division operator'},
{id:83, cz:'operátor sčítání          ', eng:'addition operator'},
{id:84, cz:'odčítání                  ', eng:'subtraction'},
{id:85, cz:'větší než                 ', eng:'greater than'},
{id:86, cz:'roven                     ', eng:'equal to'},
{id:87, cz:'menší než                 ', eng:'less than'},
{id:88, cz:'není roven                ', eng:'not equal to'},
{id:89, cz:'odkaz na buňku            ', eng:'cell reference'},
{id:90, cz:'koláčový (výsečový) graf  ', eng:'pie chart'},
{id:91, cz:'dlaždice                  ', eng:'tile'},
{id:92, cz:'zvětšení(ne zoom,enlargement)', eng:'magnification'},
{id:93, cz:'seřadit podle (ne arrange)  ', eng:'sort by'},
{id:94, cz:'vzestupně (seřadit)       ', eng:'ascending'},
{id:95, cz:'sestupně (seřadit)        ', eng:'descending'},



]

export default Level2;