const Level3 =[
    {id:1, cz:'víko (notebooku)          ', eng:'lid'},
    {id:2, cz:'spánek                    ', eng:'sleep'},
    {id:3, cz:'známý                     ', eng:'known'},
    {id:4, cz:'omezení(ne constraints,limit)', eng:'restriction'},
    {id:5, cz:'patřit                    ', eng:'belong'},
    {id:6, cz:'jedinečný                 ', eng:'unique'},
    {id:7, cz:'přiřazení                 ', eng:'assignment'},
    {id:8, cz:'vypršet                   ', eng:'expire'},
    {id:9, cz:'pasivovat,zneschopnit(ne disabl', eng:'inhibit'},
    {id:10, cz:'práva                     ', eng:'rights'},
    {id:11, cz:'zrušit (ne discard,cancel)', eng:'revoke'},
    {id:12, cz:'všichni (ne all)          ', eng:'everyone'},
    {id:13, cz:'skupina, seskupit         ', eng:'group'},
    {id:14, cz:'řada, fronta              ', eng:'queue'},
    {id:15, cz:'stav                      ', eng:'status'},
    {id:16, cz:'připojit(ne join,connect,link', eng:'attach'},
    {id:17, cz:'přihlásit                 ', eng:'log in'},
    {id:18, cz:'uvědomit                  ', eng:'notify'},
    {id:19, cz:'služba                    ', eng:'service'},
    {id:20, cz:'rovný s rovným            ', eng:'peer-to-peer'},
    {id:21, cz:'vetřelec                  ', eng:'intruder'},
    {id:22, cz:'uzamčení                  ', eng:'lockout'},
    {id:23, cz:'nouze, havárie            ', eng:'emergency'},
    {id:24, cz:'malé zdokonalení programu ', eng:'update'},
    {id:25, cz:'zůstat (ne stay)          ', eng:'remain'},
    {id:26, cz:'potlačit                  ', eng:'suppress'},
    {id:27, cz:'popis                     ', eng:'description'},
    {id:28, cz:'odmítnout (refuse)        ', eng:'reject'},
    {id:29, cz:'zadržet (ne retain)            ', eng:'hold'},
    {id:30, cz:'odsunout, pozdržet        ', eng:'defer'},
    {id:31, cz:'pořadí (ne order)         ', eng:'sequence'},
    {id:32, cz:'zařadit tisk.úlohu do front', eng:'submit print job'},
    {id:33, cz:'podle                     ', eng:'according to'},
    {id:34, cz:'vzor (maska) hledání      ', eng:'search pattern'},
    {id:35, cz:'pověřenec, důvěrník       ', eng:'trustee'},
    {id:36, cz:'zrušit,stornovat(ne cancel)', eng:'discard'},
    {id:37, cz:'oddělovač (položek seznamu)', eng:'delimiter'},
    {id:38, cz:'vyhrazený                 ', eng:'dedicated'},
    {id:39, cz:'kopie (ne copy)           ', eng:'replica'},
    {id:40, cz:'včetně                    ', eng:'including'},
    {id:41, cz:'výhoda                    ', eng:'advantage'},
    {id:42, cz:'bez ohledu na             ', eng:'regardless'},
    {id:43, cz:'dříve než                 ', eng:'prior to'},
    {id:44, cz:'týkající se(ne concerning)', eng:'regarding'},
    {id:45, cz:'podezřívat                ', eng:'suspect'},
    {id:46, cz:'ztráta                    ', eng:'loss'},
    {id:47, cz:'čitelný                   ', eng:'legible'},
    {id:48, cz:'přibližný                 ', eng:'approximate'},
    {id:49, cz:'trpět                     ', eng:'suffer'},
    {id:50, cz:'zlepšit                   ', eng:'improve'},
    {id:51, cz:'týkat se (ne regard)      ', eng:'concern'},
    {id:52, cz:'účel                      ', eng:'purpose'},
    {id:53, cz:'odhadnout                 ', eng:'estimate'},
    {id:54, cz:'uzel                      ', eng:'node'},
    {id:55, cz:'dotaz (ne request,question)', eng:'query'},
    {id:56, cz:'spolehlivost              ', eng:'reliability'},
    {id:57, cz:'vydání (ne issue,release) ', eng:'edition'},
    {id:58, cz:'za předpokladu            ', eng:'providing'},
    {id:59, cz:'dodávka                   ', eng:'delivery'},
    {id:60, cz:'moudrý,rozumný(ne reasonable)', eng:'wise'},
    {id:61, cz:'porušit, přestoupit       ', eng:'violate'},
    {id:62, cz:'smysl                     ', eng:'sense'},
    {id:63, cz:'prospěch                  ', eng:'benefit'},
    {id:64, cz:'vyvolat (ne invoke)          ', eng:'excite'},
    {id:65, cz:'nabídnout                 ', eng:'offer'},
    {id:66, cz:'zahrnovat(ne include,contain)', eng:'comprise'},
    {id:67, cz:'chod, tempo               ', eng:'pace'},
    {id:68, cz:'nezbytný, nutný           ', eng:'necessary'},
    {id:69, cz:'žádost,požadavek(ne request', eng:'demand'},
    {id:70, cz:'podobný (ne like)         ', eng:'similar'},
    {id:71, cz:'spojit,připojit(ne attach,link', eng:'join'},
    {id:72, cz:'dodavatel, obchodník        ', eng:'vendor'},
    {id:73, cz:'způsob (ne way)           ', eng:'manner'},
    {id:74, cz:'důvod                     ', eng:'reason'},
    {id:75, cz:'sídlit                    ', eng:'reside'},
    {id:76, cz:'sada, komplet (ne set,kit)', eng:'suite'},
    {id:77, cz:'sada, komplet (ne set,suite)', eng:'kit'},
    {id:78, cz:'úroveň (ne level)         ', eng:'grade'},
    {id:79, cz:'sledovaní událostí        ', eng:'auditing'},
    {id:80, cz:'letní čas                 ', eng:'daylight saving time'},
    {id:81, cz:'předávání                 ', eng:'forwarding'},
    {id:82, cz:'rámec (protokolový)        ', eng:'frame'},
    {id:83, cz:'protokolový soubor        ', eng:'log file'},
    {id:84, cz:'důležitý, základní, hlavní', eng:'fundamental'},
    {id:85, cz:'využívat (ne use, utilize)', eng:'take advantage'},
    {id:86, cz:'využívat(ne use,take advantage)', eng:'utilize'},
    {id:87, cz:'nezávislý, samostatný     ', eng:'independent'},
    {id:88, cz:'zdali                     ', eng:'whether'},
    {id:89, cz:'popisovat                 ', eng:'describe'},
    {id:90, cz:'umístit (ne place,deploy)  ', eng:'locate'},
    {id:91, cz:'hlavní(ne fundamental,main)', eng:'major'},
    {id:92, cz:'provádět,zpracovávat(ne execut ', eng:'process'},
    {id:93, cz:'nefunkční                 ', eng:'inoperable'},
    {id:94, cz:'přímý, nasměrovat             ', eng:'direct'},
    {id:95, cz:'zkratka (ne shortcut)     ', eng:'abbreviation'},
    {id:96, cz:'rozlišovat                ', eng:'distinguish'},
    {id:97, cz:'odlišný (ne alternate)    ', eng:'different'},
    {id:98, cz:'shromáždit (ne collect)      ', eng:'gather'},
    {id:99, cz:'odpovědnost               ', eng:'responsibility'},
    {id:100, cz:'vrstva                    ', eng:'layer'},
    {id:101, cz:'termín                    ', eng:'term'},
    {id:102, cz:'výstraha,pozornost,opatrnost)', eng:'caution'},
    {id:103, cz:'po dokončení              ', eng:'upon completion'},
    {id:104, cz:'široké spektrum           ', eng:'wide range'},
    {id:105, cz:'ladit                     ', eng:'tune'},
    {id:106, cz:'příkaz (v programu)       ', eng:'statement'},
    {id:107, cz:'příkaz, povel (např. v MSDOS)', eng:'command'},
    {id:108, cz:'náhodný (ve významu nehody)', eng:'accidental'},
    {id:109, cz:'příležitostný,náhodný(ne random', eng:'occasional'},
    {id:110, cz:'příležitostný,náhodný (ne occas', eng:'random'},



]

export default Level3;